#!/bin/sh

# TODO: Think about if this should rmdir MyDocs when uninstalled

xdg_dirs="
	/home/user
	/home/user/.config
	/home/user/MyDocs
	/home/user/MyDocs/.documents
	/home/user/MyDocs/.sounds
	/home/user/MyDocs/.images
	/home/user/MyDocs/.videos
	/home/user/MyDocs/DCIM
"

case "$1" in
# TODO: remove "upgrade" at some point
install|upgrade)
	for i in $xdg_dirs; do
		mkdir -p "$i"
		chown user:user "$i"
	done
	;;
esac

#DEBHELPER#
