#!/bin/sh

# Clean up old files.
rm -f /etc/X11/xorg.conf.d/40-input.conf
rm -f /etc/X11/xorg.conf.d/40-ts.conf
rm -f /etc/X11/xorg.conf.d/99-omap.conf
rm -f /etc/udev/rules.d/55-modem.rules

echo "Updating udev hwdb"
udevadm hwdb --update
udevadm trigger

# Let udevadm settle
sleep 3
# Refresh touchscreen rotation which gets borked on udevadm trigger.
/usr/bin/hildon-desktop-rotate-touchscreen.sh 2>/dev/null || true

#DEBHELPER#

exit 0
