#!/bin/sh

# Clean up old files.
rm -f /etc/X11/xorg.conf.d/40-input.conf
rm -f /etc/X11/xorg.conf.d/40-ts.conf
rm -f /etc/X11/xorg.conf.d/99-omap.conf
rm -f /etc/udev/rules.d/55-modem.rules

echo "Updating udev hwdb"
udevadm hwdb --update
udevadm trigger

if egrep -q '^none /sys/kernel/debug debugfs defaults 0 0' /etc/fstab; then
    # No need to change anything
    true;
else
    echo "none /sys/kernel/debug debugfs defaults 0 0" >> /etc/fstab
fi

#DEBHELPER#

exit 0
